---
- hosts: all
  become: true
  remote_user: ansible
  tasks:
    - name: install bind
      apt:
        name:
          - bind9
          - bind9-utils
          - bind9-dnsutils
        state: latest
        update_cache: true

    - name: set bind to run on IPv4 only
      ansible.builtin.lineinfile:
        path: /etc/default/named
        regexp: '^OPTIONS='
        line: 'OPTIONS="-u bind -4"'

    - name: overwrite named.conf.options
      template:
        src: "okd-dns-1/named.conf.options.j2"
        dest: "/etc/bind/named.conf.options"

    - name: overwrite named.conf.local
      template:
        src: "okd-dns-1/named.conf.local.j2"
        dest: "/etc/bind/named.conf.local"

    - name: restart bind
      ansible.builtin.service:
        name: named
        state: restarted