---
- hosts: all
  become: true
  remote_user: ansible
  tasks:

    - name: install keepalived
      apt:
        name: keepalived

    - name: configure keepalived
      template:
        src: "okd-loadbalancer-0/keepalived.conf.j2"
        dest: "/etc/keepalived/keepalived.conf"

    - name: restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted

    - name: set ip_bind_nonlocal
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: 1
        sysctl_set: true
        state: present
        reload: true

    - name: install haproxy
      apt:
        name:
          - haproxy
        state: latest
        update_cache: true

    - name: install haproxy configuration
      template:
        src: "okd-loadbalancer-0/haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted