---
- name: Setup dns servers
  remote_user: ansible
  become: true
  hosts: dnsservers
  roles:
    - dns

- name: Setup loadbalancers
  remote_user: ansible
  become: true
  hosts: loadbalancers
  roles:
    - loadbalancer

- name: Setup webservers
  remote_user: ansible
  become: true
  hosts: webservers
  roles:
    - web
