---
- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived

- name: Configure keepalived
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart keepalived services"

- name: Set ip_bind_nonlocal
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: Install haproxy configuration
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart haproxy services"
