---
- name: Configure bind9 DNS
  hosts: all
  become: true
  remote_user: ansible
  tasks:
    - name: Install bind
      ansible.builtin.apt:
        name:
          - bind9
          - bind9-utils
          - bind9-dnsutils
        update_cache: true

    - name: Set bind to run on IPv4 only
      ansible.builtin.lineinfile:
        path: /etc/default/named
        regexp: '^OPTIONS='
        line: 'OPTIONS="-u bind -4"'
      notify: "restart bind services"

    - name: Overwrite named.conf.options
      ansible.builtin.template:
        src: "okd-dns-1/named.conf.options.j2"
        dest: "/etc/bind/named.conf.options"
        mode: 'u=rw,g=r,o=r'
        owner: root
      notify: "restart bind services"

    - name: Overwrite named.conf.local
      ansible.builtin.template:
        src: "okd-dns-1/named.conf.local.j2"
        dest: "/etc/bind/named.conf.local"
        mode: 'u=rw,g=r,o=r'
        owner: root
      notify: "restart bind services"
