---
- name: Install bind
  ansible.builtin.apt:
    name:
      - bind9
      - bind9-utils
      - bind9-dnsutils
    update_cache: true

- name: Overwrite named.conf.options
  ansible.builtin.template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart bind services"

- name: Overwrite named.conf.local
  ansible.builtin.template:
    src: "named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart bind services"

- name: Create zones folder on primary
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart bind services"
  when: bind_server_type == 'primary'

- name: Install forward zone on primary
  ansible.builtin.copy:
    src: "zones/db.okd.home.mawson.tech"
    dest: "/etc/bind/zones/db.okd.home.mawson.tech"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart bind services"
  when: bind_server_type == 'primary'

- name: Install reverse zone on primary
  ansible.builtin.copy:
    src: "zones/db.56.10.10.in-addr.arpa"
    dest: "/etc/bind/zones/db.56.10.10.in-addr.arpa"
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: "restart bind services"
  when: bind_server_type == 'primary'
